# Generated by Django 5.1.3 on 2024-11-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('prezzo_fv', models.FloatField()),
                ('prezzo_storage', models.FloatField()),
                ('prezzo_trainante', models.FloatField()),
                ('potenza_installata', models.FloatField()),
                ('storage_installato', models.FloatField()),
                ('producibilita_specifica', models.FloatField()),
                ('produzione_annua', models.FloatField()),
                ('tipologia_moduli', models.FloatField()),
            ],
        ),
    ]
