# Generated by Django 5.1.3 on 2024-11-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0002_remove_offerta_prezzo_fv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerta',
            old_name='bilancio_primo_anno',
            new_name='bilancio_decimo_anno',
        ),
    ]
