# Generated by Django 5.1.3 on 2024-11-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0002_alter_offerta_potenza_installata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerta',
            name='slug',
            field=models.SlugField(),
        ),
    ]
