# Generated by Django 5.1.3 on 2024-11-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0003_rename_bilancio_primo_anno_offerta_bilancio_decimo_anno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerta',
            old_name='bilancio_decimo_anno',
            new_name='bilancio_dieci_anni',
        ),
    ]
