# Generated by Django 5.1.3 on 2024-11-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0004_rename_prezzo_fv_offerta_aliquota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerta',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
