# Generated by Django 5.1.3 on 2024-11-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0006_alter_offerta_costi_energia_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerta',
            name='consumi_cliente',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='costi_energia_cliente',
            field=models.FloatField(default=float("nan"), null=True),
        ),
    ]
