# Generated by Django 5.1.3 on 2024-11-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0008_alter_offerta_consumi_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerta',
            name='costi_energia_cliente',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='tariffa_energia_cliente',
            field=models.FloatField(default='Inserire dati bolletta', null=True),
        ),
    ]
