# Generated by Django 5.1.3 on 2024-11-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0010_alter_offerta_tariffa_energia_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='risparmi',
            field=models.FloatField(null=True),
        ),
    ]
