# Generated by Django 5.1.3 on 2024-11-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0011_offerta_risparmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerta',
            name='risparmi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
