# Generated by Django 5.1.3 on 2024-11-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0012_alter_offerta_risparmi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerta',
            old_name='risparmi',
            new_name='risparmi_bolletta',
        ),
        migrations.AddField(
            model_name='offerta',
            name='risparmio_bolletta_primo_anno',
            field=models.FloatField(null=True),
        ),
    ]
