# Generated by Django 5.1.3 on 2024-11-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0013_rename_risparmi_offerta_risparmi_bolletta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='risparmio_totale_primo_anno',
            field=models.FloatField(null=True),
        ),
    ]
