# Generated by Django 5.1.3 on 2024-11-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0015_offerta_risparmio_dieci_anni'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='anticipo_leasing',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='importo_leasing',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='prima_rata',
            field=models.FloatField(null=True),
        ),
    ]
