# Generated by Django 5.1.3 on 2024-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0016_offerta_anticipo_leasing_offerta_importo_leasing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerta',
            name='aliquota',
            field=models.FloatField(default=0.15, null=True),
        ),
    ]
