# Generated by Django 5.1.3 on 2024-11-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0017_alter_offerta_aliquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='delta_leasing_primo_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='leasing_primo_anno',
            field=models.FloatField(null=True),
        ),
    ]
