# Generated by Django 5.1.3 on 2024-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0018_offerta_delta_leasing_primo_anno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='delta_leasing_decimo_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='delta_leasing_nono_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='delta_leasing_ottavo_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='delta_leasing_quarto_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='delta_leasing_quinto_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='delta_leasing_secondo_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='delta_leasing_sesto_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='delta_leasing_settimo_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='delta_leasing_terzo_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='leasing_decimo_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='leasing_nono_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='leasing_ottavo_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='leasing_quarto_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='leasing_quinto_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='leasing_secondo_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='leasing_sesto_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='leasing_settimo_anno',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='leasing_terzo_anno',
            field=models.FloatField(null=True),
        ),
    ]
