# Generated by Django 5.1.3 on 2024-11-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0020_offerta_delta_totale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerta',
            name='delta_totale',
        ),
    ]
