# Generated by Django 5.1.3 on 2024-11-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0021_remove_offerta_delta_totale'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='delta_leasing_totale',
            field=models.FloatField(null=True),
        ),
    ]
