# Generated by Django 5.1.3 on 2024-11-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0022_offerta_delta_leasing_totale'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='totale_check',
            field=models.FloatField(null=True),
        ),
    ]
