# Generated by Django 5.1.3 on 2024-11-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0023_offerta_totale_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='delta_totale_check',
            field=models.FloatField(null=True),
        ),
    ]
