# Generated by Django 5.1.3 on 2024-11-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0027_alter_offerta_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerta',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
