# Generated by Django 5.1.3 on 2024-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0028_alter_offerta_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
