# Generated by Django 5.1.3 on 2024-11-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPC_5_0_v02', '0029_offerta_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerta',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
