# Generated by Django 5.1 on 2024-10-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impianto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_impianto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produzione_annua', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
